name: React CI/CD
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22.x
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: "Setup Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "${{ matrix.node-version }}"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Remove unused imports
        run: pnpm run lint-fix
      - name: Build project
        run: pnpm run build
      - name: List all files
        run: ls -R .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-files
          path: dist/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          folder: dist
          branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: build-files
          
      - name: Extract build artifacts
        run: |
          mkdir dist
          tar -xvf ${{ github.workspace }}/dist.tar.gz -C dist
      - name: List all files
        run: ls -R .
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          folder: dist
          branch: gh-pages
